# Generated by Django 5.2.9 on 2025-12-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_feedback',
            field=models.JSONField(blank=True, default=dict, help_text='AI-generated educational feedback after grading'),
        ),
    ]
